; This script was created using Pulover's Macro Creator
; www.macrocreator.com

#NoEnv
SetWorkingDir %A_ScriptDir%
CoordMode, Mouse, Window
SendMode Input
#SingleInstance Force
SetTitleMatchMode 2
#WinActivateForce
SetControlDelay 1
SetWinDelay 0
SetKeyDelay -1
SetMouseDelay -1
SetBatchLines -1


::
Macro1:
WinActivate, MeshLab 2016.12 - [Project_1] ahk_class Qt5QWindowIcon
Sleep, 333
Sleep, 300
Click, 858, 541 Left, Down
Click, 858, 541 Left, Up
Sleep, 200
Send, {LShift Down}
Sleep, 100
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Click, WheelDown
Sleep, 100
Send, {LShift Up}
Sleep, 100
Click, 1740, 661 Left, Down
Sleep, 100
Click, 1740, 661 Left, Up
Sleep, 100
Click, 1822, 702 Left, Down
Sleep, 100
Click, 1822, 702 Left, Up
Sleep, 100
Send, {LAlt Down}
Sleep, 25
Send, {f}
Sleep, 25
Send, {LAlt Up}
Sleep, 25
Send, {t}
Sleep, 25
Sleep, 100
WinActivate, Save snapshot ahk_class Qt5QWindowIcon
Send, {Tab}
Sleep, 25
Send, {Tab}
Sleep, 25
Send, {LControl Down}
Sleep, 25
Send, {v}
Sleep, 25
Send, {LControl Up}
Sleep, 25
Send, {Backspace}
Sleep, 25
Send, {Tab}
Sleep, 25
Send, {Tab}
Sleep, 25
Send, {Tab}
Sleep, 25
Send, {Tab}
Sleep, 25
Send, {Down}
Sleep, 25
Send, {Tab}
Sleep, 25
Send, {Tab}
Sleep, 25
Send, {Tab}
Sleep, 25
Send, {Tab}
Sleep, 25
Click, 1825, 617, 0
WinActivate, MeshLab 2016.12 - [Project_1] ahk_class Qt5QWindowIcon
Send, {Enter}
Sleep, 25
Send, {LControl Down}
Sleep, 25
Send, {q}
Sleep, 25
Send, {LControl Up}
Sleep, 200
Return

